
name = "DashFacebookLogin"
uuid = "1b08a953-4be3-4667-9a23-2f8a1ec8e0d1"
authors = ["Miklos Danka <danka.miklos@gmail.com>"]
version = "0.0.2"

[deps]
Dash = "1b08a953-4be3-4667-9a23-3db579824955"

[compat]
julia = "1.2"
Dash = "0.1.3"
